package sarc_reglas.adopcion;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Adopcion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Adopcion() {
    }


	/** Globales */
	
	public final static String STRING_RESPUESTA_DROOLS = "NO_HAY_RESPUESTA_DE_DROOLS";

	/** Valores de comparacion */
	
	public final static String TIPO_REGISTRO_INSCRIPCION 		= "INSCRIPCION";
	public final static String TIPO_REGISTRO_DECISION_JUDICIAL 	= "DECISION_JUDICIAL";

	public final static String CASO_MADRE_Y_PADRE_PRESENTES 				= "MADRE_Y_PADRE_PRESENTES";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_ADOPTADO_CON_ID = "MADRE_Y_PADRE_PRESENTES_ADOPTADO_CON_ID";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_ADOPTADO_SIN_ID = "MADRE_Y_PADRE_PRESENTES_ADOPTADO_SIN_ID";

	public final static String CASO_MADRE_O_PADRE_PRESENTES 				= "MADRE_O_PADRE_PRESENTES";
	public final static String CASO_MADRE_O_PADRE_PRESENTES_ADOPTADO_CON_ID = "MADRE_O_PADRE_PRESENTES_ADOPTADO_ID";
	public final static String CASO_MADRE_O_PADRE_PRESENTES_ADOPTADO_SIN_ID = "MADRE_O_PADRE_PRESENTES_ADOPTADO_SIN_ID";

	/** Acciones de redireccion */

	public final static String ACCION_VISTA_INSCRIPCION 		= "inscripcion_vista";
	public final static String ACCION_VISTA_DECISION_JUDICIAL 	= "decision_judicial_vista";

	public final static String ACCION_VISTA_MADRE_Y_PADRE_PRESENTES					= "madre_y_padre_presentes_vista";
	public final static String ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_ADOPTADO_CON_ID = "madre_y_padre_presentes_adoptado_con_id_vista";
	public final static String ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_ADOPTADO_SIN_ID = "madre_y_padre_presentes_adoptado_sin_id_vista";

	public final static String ACCION_VISTA_MADRE_PRESENTE = "madre_presente_vista";
	public final static String ACCION_VISTA_PADRE_PRESENTE = "padre_presente_vista";

	public final static String ACCION_VISTA_MADRE_O_PADRE_PRESENTES_ADOPTADO_CON_ID = "madre_o_padre_presentes_adoptado_con_id_vista";
	public final static String ACCION_VISTA_MADRE_O_PADRE_PRESENTES_ADOPTADO_SIN_ID = "madre_o_padre_presentes_adoptado_sin_id_vista";

	/** Acciones de respuesta */
	
	private Boolean continuarEvaluando = true;
	
	private String accion;
	private String escenario;
	private String tipoRegistro;
	private String casoTramite;
	
	private Boolean estaMadrePresente;
	private Boolean estaPadrePresente;
	private Boolean estaMadreYPadrePresentes;
	private Boolean estaAdoptadoConID;
	private Boolean estaTestigo1Presente;
	private Boolean estaTestigo2Presente;
	
	public Boolean getContinuarEvaluando() {
		return continuarEvaluando;
	}
	
	public void setContinuarEvaluando(Boolean continuarEvaluando) {
		this.continuarEvaluando = continuarEvaluando;
	}
	
	public String getAccion() {
		return accion;
	}
	
	public void setAccion(String accion) {
		this.accion = accion;
	}
	
	public String getEscenario() {
		return escenario;
	}
	
	public void setEscenario(String escenario) {
		this.escenario = escenario;
	}
	
	public String getTipoRegistro() {
		return tipoRegistro;
	}
	
	public void setTipoRegistro(String tipoRegistro) {
		this.tipoRegistro = tipoRegistro;
	}
	
	public String getCasoTramite() {
		return casoTramite;
	}
	
	public void setCasoTramite(String casoTramite) {
		this.casoTramite = casoTramite;
	}
	
	public Boolean getEstaMadrePresente() {
		return estaMadrePresente;
	}
	
	public void setEstaMadrePresente(Boolean estaMadrePresente) {
		this.estaMadrePresente = estaMadrePresente;
	}
	
	public Boolean getEstaPadrePresente() {
		return estaPadrePresente;
	}
	
	public void setEstaPadrePresente(Boolean estaPadrePresente) {
		this.estaPadrePresente = estaPadrePresente;
	}
	
	public Boolean getEstaMadreYPadrePresentes() {
		return estaMadreYPadrePresentes;
	}
	
	public void setEstaMadreYPadrePresentes(Boolean estaMadreYPadrePresentes) {
		this.estaMadreYPadrePresentes = estaMadreYPadrePresentes;
	}

	public Boolean getEstaAdoptadoConID() {
		return estaAdoptadoConID;
	}

	public void setEstaAdoptadoConID(Boolean estaAdoptadoConID) {
		this.estaAdoptadoConID = estaAdoptadoConID;
	}

	public Boolean getEstaTestigo1Presente() {
		return estaTestigo1Presente;
	}

	public void setEstaTestigo1Presente(Boolean estaTestigo1Presente) {
		this.estaTestigo1Presente = estaTestigo1Presente;
	}

	public Boolean getEstaTestigo2Presente() {
		return estaTestigo2Presente;
	}

	public void setEstaTestigo2Presente(Boolean estaTestigo2Presente) {
		this.estaTestigo2Presente = estaTestigo2Presente;
	}

}